### ISSUE TITLE
Can't disconnect from Chromecast

### ISSUE THREAD

**Issue by mittsquared** [terrabythia/dart_chromecast#3]
Hi, so I am trying to integrate Chromecast into my media player and noticed that my app cannot disconnect from the device no matter what state it is in. Calling `CastSender.disconnect()` outputs this to the debug console:

```
I/flutter (16022): Send: protocolVersion: CASTV2_1_0
I/flutter (16022): sourceId: client-56436
I/flutter (16022): destinationId: 4da28398-839c-4e8e-8dbe-30b1cb7a73bf
I/flutter (16022): namespace: urn:x-cast:com.google.cast.media
I/flutter (16022): payloadType: STRING
I/flutter (16022): payloadUtf8: {"mediaSessionId":1,"type":"STOP","requestId":28}
I/flutter (16022): List: [0, 0, 0, 141, 8, 0, 18, 12, 99, 108, 105, 101, 110, 116, 45, 53, 54, 52, 51, 54, 26, 36, 52, 100, 97, 50, 56, 51, 57, 56, 45, 56, 51, 57, 99, 45, 52, 101, 56, 101, 45, 56, 100, 98, 101, 45, 51, 48, 98, 49, 99, 98, 55, 97, 55, 51, 98, 102, 34, 32, 117, 114, 110, 58, 120, 45, 99, 97, 115, 116, 58, 99, 111, 109, 46, 103, 111, 111, 103, 108, 101, 46, 99, 97, 115, 116, 46, 109, 101, 100, 105, 97, 40, 0, 50, 49, 123, 34, 109, 101, 100, 105, 97, 83, 101, 115, 115, 105, 111, 110, 73, 100, 34, 58, 49, 44, 34, 116, 121, 112, 101, 34, 58, 34, 83, 84, 79, 80, 34, 44, 34, 114, 101, 113, 117, 101, 115, 116, 73, 100, 34, 58, 50, 56, 125]
I/flutter (16022): Send: protocolVersion: CASTV2_1_0
I/flutter (16022): sourceId: client-56436
I/flutter (16022): destinationId: 4da28398-839c-4e8e-8dbe-30b1cb7a73bf
I/flutter (16022): namespace: urn:x-cast:com.google.cast.tp.connection
I/flutter (16022): payloadType: STRING
I/flutter (16022): payloadUtf8: {"type":"STOP","sessionId":1,"requestId":29}
I/flutter (16022): List: [0, 0, 0, 144, 8, 0, 18, 12, 99, 108, 105, 101, 110, 116, 45, 53, 54, 52, 51, 54, 26, 36, 52, 100, 97, 50, 56, 51, 57, 56, 45, 56, 51, 57, 99, 45, 52, 101, 56, 101, 45, 56, 100, 98, 101, 45, 51, 48, 98, 49, 99, 98, 55, 97, 55, 51, 98, 102, 34, 40, 117, 114, 110, 58, 120, 45, 99, 97, 115, 116, 58, 99, 111, 109, 46, 103, 111, 111, 103, 108, 101, 46, 99, 97, 115, 116, 46, 116, 112, 46, 99, 111, 110, 110, 101, 99, 116, 105, 111, 110, 40, 0, 50, 44, 123, 34, 116, 121, 112, 101, 34, 58, 34, 83, 84, 79, 80, 34, 44, 34, 115, 101, 115, 115, 105, 111, 110, 73, 100, 34, 58, 49, 44, 34, 114, 101, 113, 117, 101, 115, 116, 73, 100, 34, 58, 50, 57, 125]
I/flutter (16022): PING
E/flutter (16022): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (16022): SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 192.168.0.129, port = 49166
E/flutter (16022): #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
E/flutter (16022): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (16022): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (16022): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (16022): SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 192.168.0.129, port = 49166
E/flutter (16022): #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
E/flutter (16022): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (16022): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

Every other function (play/pause, seek, etc.) works fine. Stepping through, it gets caught on the `sessionId` getter.

**Comment by terrabythia** [comment]
Nice to know that somebody is using this in on of their applications! Do mind that this is still a very early version, so bugs like these can occur. Thanks for the heads up anyway!

Disconnecting was actually never really tested yet. I didn't get the error you got, but the device didn't disconnect either. Should now be fixed in my latest commit.

**Comment by snaeji** [comment]
@terrabythia i'm also hoping to integrate it when it gets stable enough! Will be watching you ;)
